
export class Inventory {

    constructor(
        codigo,
        cod_Articulo,
        barras,
        descripcion,
        presentaCant,
        codPresentacion,
        codMarca,
        subFamilia,
        minima,
        puntoMedio,
        maxima,
        existencia,
        subUbicacion,
        observaciones,
        monedaCosto,
        precioBase,
        fletes,
        otrosCargos,
        costo,
        monedaVenta,
        iVenta,
        precio_A,
        precio_B,
        precio_C,
        precio_D,
        precio_Promo,
        promo_Activa,
        promo_Inicio,
        promo_Finaliza,
        max_Comision,
        max_Descuento,
        servicio,
        inhabilitado,
        proveedor,
        precio_Sugerido,
        sugeridoIV,
        preguntaPrecio,
        lote,
        consignacion,
        id_Bodega,
        existenciaBodega,
        maX_Inventario,
        maX_Bodega,
        cantidadDescarga,
        codigoDescarga,
        descargaOtro,
        cod_PresentOtro,
        cantidadPresentOtro,
        existenciaForzada,
        bloqueado,
        pantalla,
        clinica,
        mascotas,
        receta,
        peces,
        taller,
        barras2,
        barras3,
        apartado,
        promo3x1,
        orden,
        bonificado,
        encargado,
        serie,
        armamento,
        tienda,
        prestamo,
        maquinaria,
        productos_organicos,
        rifa,
        promoCON,
        promoCRE,
        costoReal,
        validaExistencia,
        actualizado,
        id_Impuesto,
        activarBodega2,
        existenciaBodega2,
        enToma,
        usaGalon,
        apicarDescuentoTarjeta,
        soloContado,
        soloConExistencia,
        mag,
        sinDecimal,
        codcabys,
        codigoPrestamo,
        muestra,
        web,
        soloUsoInterno,
        categorias,
        codigoBarras,
        codigoIntQVET,
        codigoPro,
        descripcionPro,
        estado,
        idUsuarioCreacion,
        idUsuarioModificacion
    ) {
        this.codigo = codigo || 0,
        this.cod_Articulo = cod_Articulo || '',
        this.barras = barras || '',
        this.descripcion = descripcion || '',
        this.presentaCant = presentaCant || 0,
        this.codPresentacion = codPresentacion || 1,
        this.codMarca = codMarca || 1,
        this.subFamilia = subFamilia || '',
        this.minima = minima || 0,
        this.puntoMedio = puntoMedio || 0,
        this.maxima = maxima || 0,
        this.existencia = existencia || 0,
        this.subUbicacion = subUbicacion || '',
        this.observaciones = observaciones || '',
        this.monedaCosto = monedaCosto || 1,
        this.precioBase = precioBase || 0,
        this.fletes = fletes || 0,
        this.otrosCargos = otrosCargos || 0,
        this.costo = costo || 0,
        this.monedaVenta = monedaVenta || 1,
        this.iVenta = iVenta || 13,
        this.precio_A = precio_A || 0,
        this.precio_B = precio_B || 0,
        this.precio_C = precio_C || 0,
        this.precio_D = precio_D || 0,
        this.precio_Promo = precio_Promo || 0,
        this.promo_Activa = promo_Activa || false,
        this.promo_Inicio = promo_Inicio || null,
        this.promo_Finaliza = promo_Finaliza || null,
        this.max_Comision = max_Comision || 0,
        this.max_Descuento = max_Descuento || 0,
        this.servicio = servicio || false,
        this.inhabilitado = inhabilitado || false,
        this.proveedor = proveedor || 0,
        this.precio_Sugerido = precio_Sugerido || 0,
        this.sugeridoIV = sugeridoIV || 0,
        this.preguntaPrecio = preguntaPrecio || false,
        this.lote = lote || false,
        this.consignacion = consignacion || false,
        this.id_Bodega = id_Bodega || 0,
        this.existenciaBodega = existenciaBodega || 0,
        this.maX_Inventario = maX_Inventario || 0,
        this.maX_Bodega = maX_Bodega || 0,
        this.cantidadDescarga = cantidadDescarga || 0,
        this.codigoDescarga = codigoDescarga || null,
        this.descargaOtro = descargaOtro || false,
        this.cod_PresentOtro = cod_PresentOtro || 0,
        this.cantidadPresentOtro = cantidadPresentOtro || 0,
        this.existenciaForzada = existenciaForzada || 0,
        this.bloqueado = bloqueado || false,
        this.pantalla = pantalla || false,
        this.clinica = clinica || false,
        this.mascotas = mascotas || false,
        this.receta = receta || false,
        this.peces = peces || false,
        this.taller = taller || false,
        this.barras2 = barras2 || null,
        this.barras3 = barras3 || null,
        this.apartado = apartado || 0,
        this.promo3x1 = promo3x1 || false,
        this.orden = orden || false,
        this.bonificado = bonificado || false,
        this.encargado = encargado || null,
        this.serie = serie || 0,
        this.armamento = armamento || false,
        this.tienda = tienda || false,
        this.prestamo = prestamo || 0,
        this.maquinaria = maquinaria || false,
        this.productos_organicos = productos_organicos || false,
        this.rifa = rifa || 0,
        this.promoCON = promoCON || false,
        this.promoCRE = promoCRE || false,
        this.costoReal = costoReal || 0,
        this.validaExistencia = validaExistencia || false,
        this.actualizado = actualizado || false,
        this.id_Impuesto = id_Impuesto || 1,
        this.activarBodega2 = activarBodega2 || false,
        this.existenciaBodega2 = existenciaBodega2 || 0,
        this.enToma = enToma || false,
        this.usaGalon = usaGalon || false,
        this.apicarDescuentoTarjeta = apicarDescuentoTarjeta || false,
        this.soloContado = soloContado || false,
        this.soloConExistencia = soloConExistencia || false,
        this.mag = mag || false,
        this.sinDecimal = sinDecimal || false,
        this.codcabys = codcabys || '',
        this.codigoPrestamo = codigoPrestamo || 0,
        this.muestra = muestra || false,
        this.web = web || false,
        this.soloUsoInterno = soloUsoInterno || false,
        this.categorias = categorias || [],
        this.codigoBarras = codigoBarras || [],
        this.codigoIntQVET = codigoIntQVET || 0,
        this.codigoPro = codigoPro || 0,
        this.descripcionPro = descripcionPro || '',
        this.estado = estado || true,
        this.idUsuarioCreacion = idUsuarioCreacion || ''
        this.idUsuarioModificacion = idUsuarioModificacion || ''
    }

    toJson() {
        return {
            codigo                 : this.codigo,
            cod_Articulo           : this.cod_Articulo,
            barras                 : this.barras,
            descripcion            : this.descripcion,
            presentaCant           : this.presentaCant,
            codPresentacion        : this.codPresentacion,
            codMarca               : this.codMarca,
            subFamilia             : this.subFamilia,
            minima                 : this.minima,
            puntoMedio             : this.puntoMedio,
            maxima                 : this.maxima,
            existencia             : this.existencia,
            subUbicacion           : this.subUbicacion,
            observaciones          : this.observaciones,
            monedaCosto            : this.monedaCosto,
            precioBase             : this.precioBase,
            fletes                 : this.fletes,
            otrosCargos            : this.otrosCargos,
            costo                  : this.costo,
            monedaVenta            : this.monedaVenta,
            iVenta                 : this.iVenta,
            precio_A               : this.precio_A,
            precio_B               : this.precio_B,
            precio_C               : this.precio_C,
            precio_D               : this.precio_D,
            precio_Promo           : this.precio_Promo,
            promo_Activa           : this.promo_Activa,
            promo_Inicio           : this.promo_Inicio,
            promo_Finaliza         : this.promo_Finaliza,
            max_Comision           : this.max_Comision,
            max_Descuento          : this.max_Descuento,
            servicio               : this.servicio,
            inhabilitado           : this.inhabilitado,
            proveedor              : this.proveedor,
            precio_Sugerido        : this.precio_Sugerido,
            sugeridoIV             : this.sugeridoIV,
            preguntaPrecio         : this.preguntaPrecio,
            lote                   : this.lote,
            consignacion           : this.consignacion,
            id_Bodega              : this.id_Bodega,
            existenciaBodega       : this.existenciaBodega,
            maX_Inventario         : this.maX_Inventario,
            maX_Bodega             : this.maX_Bodega,
            cantidadDescarga       : this.cantidadDescarga,
            codigoDescarga         : this.codigoDescarga,
            descargaOtro           : this.descargaOtro,
            cod_PresentOtro        : this.cod_PresentOtro,
            cantidadPresentOtro    : this.cantidadPresentOtro,
            existenciaForzada      : this.existenciaForzada,
            bloqueado              : this.bloqueado,
            pantalla               : this.pantalla,
            clinica                : this.clinica,
            mascotas               : this.mascotas,
            receta                 : this.receta,
            peces                  : this.peces,
            taller                 : this.taller,
            barras2                : this.barras2,
            barras3                : this.barras3,
            apartado               : this.apartado,
            promo3x1               : this.promo3x1,
            orden                  : this.orden,
            bonificado             : this.bonificado,
            encargado              : this.encargado,
            serie                  : this.serie,
            armamento              : this.armamento,
            tienda                 : this.tienda,
            prestamo               : this.prestamo,
            maquinaria             : this.maquinaria,
            productos_organicos    : this.productos_organicos,
            rifa                   : this.rifa,
            promoCON               : this.promoCON,
            promoCRE               : this.promoCRE,
            costoReal              : this.costoReal,
            validaExistencia       : this.validaExistencia,
            actualizado            : this.actualizado,
            id_Impuesto            : this.id_Impuesto,
            activarBodega2         : this.activarBodega2,
            existenciaBodega2      : this.existenciaBodega2,
            enToma                 : this.enToma,
            usaGalon               : this.usaGalon,
            apicarDescuentoTarjeta : this.apicarDescuentoTarjeta,
            soloContado            : this.soloContado,
            soloConExistencia      : this.soloConExistencia,
            mag                    : this.mag,
            sinDecimal             : this.sinDecimal,
            codcabys               : this.codcabys,
            codigoPrestamo         : this.codigoPrestamo,
            muestra                : this.muestra,
            web                    : this.web,
            soloUsoInterno         : this.soloUsoInterno,
            categorias             : this.categorias,
            codigoBarras           : this.codigoBarras,
            idCodigoInternoQvet    : this.codigoIntQVET,
            codigoProveedor        : this.codigoPro,
            descripcionProveedor   : this.descripcionPro,
            estado                 : this.estado,
            idUsuarioCreacion      : this.idUsuarioCreacion,
            idUsuarioModificacion  : this.idUsuarioModificacion
        }
    }

}

//Objeto JSON
// {
//     "codigo": 0,
//     "cod_Articulo": "1245",
//     "barras": "12313123123",
//     "descripcion": "testPostman",
//     "presentaCant": 10,
//     "codPresentacion": 1,
//     "codMarca": 1,
//     "subFamilia": "testPostman",
//     "minima": 0,
//     "puntoMedio": 0,
//     "maxima": 0,
//     "existencia": 0,
//     "subUbicacion": "testPostman",
//     "observaciones": null,
//     "monedaCosto": 1,
//     "precioBase": 5000,
//     "fletes": 0,
//     "otrosCargos": 0,
//     "costo": 0,
//     "monedaVenta": 1,
//     "iVenta": 13,
//     "precio_A": 5000,
//     "precio_B": 0,
//     "precio_C": 0,
//     "precio_D": 0,
//     "precio_Promo": 0,
//     "promo_Activa": false,
//     "promo_Inicio": null,
//     "promo_Finaliza": null,
//     "max_Comision": 0,
//     "max_Descuento": 0,
//     "servicio": false,
//     "inhabilitado": false,
//     "proveedor": 0,
//     "precio_Sugerido": 0,
//     "sugeridoIV": 0,
//     "preguntaPrecio": false,
//     "lote": false,
//     "consignacion": false,
//     "id_Bodega": 0,
//     "existenciaBodega": 0,
//     "maX_Inventario": 0,
//     "maX_Bodega": 0,
//     "cantidadDescarga": 0,
//     "codigoDescarga": null,
//     "descargaOtro": false,
//     "cod_PresentOtro": 0,
//     "cantidadPresentOtro": 0,
//     "existenciaForzada": 0,
//     "bloqueado": false,
//     "pantalla": false,
//     "clinica": false,
//     "mascotas": false,
//     "receta": false,
//     "peces": false,
//     "taller": false,
//     "barras2": null,
//     "barras3": null,
//     "apartado": 0,
//     "promo3x1": false,
//     "orden": false,
//     "bonificado": false,
//     "encargado": null,
//     "serie": 0,
//     "armamento": false,
//     "tienda": false,
//     "prestamo": 0,
//     "maquinaria": false,
//     "productos_organicos": false,
//     "rifa": 0,
//     "promoCON": false,
//     "promoCRE": false,
//     "costoReal": 0,
//     "validaExistencia": false,
//     "actualizado": false,
//     "id_Impuesto": 1,
//     "activarBodega2": false,
//     "existenciaBodega2": 0,
//     "enToma": false,
//     "usaGalon": false,
//     "apicarDescuentoTarjeta": false,
//     "soloContado": false,
//     "soloConExistencia": false,
//     "mag": false,
//     "sinDecimal": false,
//     "codcabys": "1323131232323",
//     "codigoPrestamo": 0,
//     "muestra": false,
//     "web": false,
//     "soloUsoInterno": false,
//     "estado": true,
//     "idUsuarioCreacion": "testPostman",
//     "idUsuarioModificacion": "testPostman"
// }